### ISSUE TITLE
PAYER should be PLAYER

### ISSUE THREAD

**Issue by sodface** [TAAPArthur/SystemConfig#1]
https://github.com/TAAPArthur/SystemConfig/blob/87679351cf917405e511d47ebe7f4967fe8dd7b8/Config/.profile#L22

Just trying to see how you are launching sgestures and noticed this typo(?) so I thought I would point it out.

**Comment by sodface** [comment]
@TAAPArthur I opened this a while ago when I was going through your repos for the project I was working on, not sure if you saw this or the other issue? Should I just close these?

**Comment by TAAPArthur** [comment]
Thanks. I missed the notification. Should be fixed now
